# Copyright Contributors to the Open Cluster Management project

apiVersion: apps/v1
kind: Deployment
metadata:
  name: managedcluster-import-controller
spec:
  template:
    spec:
      containers:
      - name: managedcluster-import-controller
        image: quay.io/open-cluster-management/managedcluster-import-controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: REGISTRATION_OPERATOR_IMAGE
          value: "quay.io/open-cluster-management/registration-operator:latest"
        - name: REGISTRATION_IMAGE
          value: "quay.io/open-cluster-management/registration:latest"
        - name: WORK_IMAGE
          value: "quay.io/open-cluster-management/work:latest"